/**
 * @file Hardcoded template object for React Flow demo
 */
import { Types, Type, Tag, UpdatedBy } from "./TemplateTypes";

export const mockUpdatedBy: UpdatedBy = {
  BEMSID: "B1234567",
  CREATED_ON: new Date("2023-01-15"),
  EMAIL: "john.doe@boeing.com",
  EQUIPMENT_MANAGER: "EM-001",
  IS_ACTIVE: "Y",
  LAB_ID: "LAB-42",
  NAME: "John Doe",
  NT_USER_ID: "nt\\jdoe",
  PHONE_1: "555-0101",
  PHONE_2: "555-0102",
  ROLES: "Engineer",
  TITLE: "Senior Systems Engineer",
  UPDATED_ON: new Date("2024-06-01"),
  id: 1,
  node_type: "UpdatedBy",
};

export const mockTags: Tag[] = [
  {
    Description: "Aerospace structural requirements",
    NAME: "Aerospace",
    UPDATED_ON: new Date("2024-05-20"),
    node_type: "Tag",
    id: 101,
  },
  {
    Description: "Safety critical components",
    NAME: "Safety",
    UPDATED_ON: new Date("2024-05-21"),
    node_type: "Tag",
    id: 102,
  },
];

export const HARDCODED_TEMPLATE: Types = {
  UniqueID: "tpl-root-001",
  display: true,
  description: "Master SOW template for commercial aircraft systems",
  type: Type.Template,
  UPDATED_ON: new Date("2024-06-01"),
  sponsoring_customer: "Boeing Commercial Airplanes",
  node_type: Type.Template,
  isDeleted2: false,
  header: "Aircraft Systems SOW",
  inputType: "template",
  id: 1,
  choices: [],
  hasInput: false,
  prompt: "Top-level statement of work template",
  children: [
    {
      UniqueID: "tpl-sec-001",
      display: true,
      description: "Scope of work overview",
      type: Type.RequirementObject,
      UPDATED_ON: new Date("2024-06-01"),
      sponsoring_customer: "Boeing Commercial Airplanes",
      node_type: Type.RequirementObject,
      isDeleted2: false,
      header: "1. Scope",
      inputType: "section",
      id: 2,
      choices: [],
      hasInput: true,
      prompt: "Describe the overall scope",
      order: 1,
      children: [
        {
          UniqueID: "tpl-sub-001",
          display: true,
          description: "System boundaries",
          type: Type.RequirementObject,
          UPDATED_ON: new Date("2024-06-01"),
          sponsoring_customer: "Boeing Commercial Airplanes",
          node_type: Type.RequirementObject,
          isDeleted2: false,
          header: "1.1 System Boundaries",
          inputType: "textarea",
          id: 3,
          choices: [],
          hasInput: true,
          prompt: "Define system boundaries",
          order: 1,
          children: [],
          Tag: [mockTags[0]],
        },
        {
          UniqueID: "tpl-sub-002",
          display: true,
          description: "Exclusions from scope",
          type: Type.RequirementObject,
          UPDATED_ON: new Date("2024-06-01"),
          sponsoring_customer: "Boeing Commercial Airplanes",
          node_type: Type.RequirementObject,
          isDeleted2: false,
          header: "1.2 Exclusions",
          inputType: "textarea",
          id: 4,
          choices: [],
          hasInput: true,
          prompt: "List scope exclusions",
          order: 2,
          children: [],
          Tag: [mockTags[1]],
        },
      ],
      Tag: [mockTags[0]],
    },
    {
      UniqueID: "tpl-sec-002",
      display: true,
      description: "Technical requirements",
      type: Type.RequirementObject,
      UPDATED_ON: new Date("2024-06-01"),
      sponsoring_customer: "Boeing Commercial Airplanes",
      node_type: Type.RequirementObject,
      isDeleted2: false,
      header: "2. Technical Requirements",
      inputType: "section",
      id: 5,
      choices: [],
      hasInput: true,
      prompt: "Specify technical requirements",
      order: 2,
      children: [
        {
          UniqueID: "tpl-sub-003",
          display: true,
          description: "Performance specs",
          type: Type.RequirementObject,
          UPDATED_ON: new Date("2024-06-01"),
          sponsoring_customer: "Boeing Commercial Airplanes",
          node_type: Type.RequirementObject,
          isDeleted2: false,
          header: "2.1 Performance",
          inputType: "select",
          id: 6,
          choices: ["Level A", "Level B", "Level C"],
          hasInput: true,
          prompt: "Select performance level",
          order: 1,
          children: [
            {
              UniqueID: "tpl-sub-sub-001",
              display: true,
              description: "Latency requirement",
              type: Type.RequirementObject,
              UPDATED_ON: new Date("2024-06-01"),
              sponsoring_customer: "Boeing Commercial Airplanes",
              node_type: Type.RequirementObject,
              isDeleted2: false,
              header: "2.1.1 Latency",
              inputType: "number",
              id: 7,
              choices: [],
              hasInput: true,
              prompt: "Max latency in ms",
              order: 1,
              children: [],
            },
            {
              UniqueID: "tpl-sub-sub-002",
              display: true,
              description: "Throughput requirement",
              type: Type.RequirementObject,
              UPDATED_ON: new Date("2024-06-01"),
              sponsoring_customer: "Boeing Commercial Airplanes",
              node_type: Type.RequirementObject,
              isDeleted2: false,
              header: "2.1.2 Throughput",
              inputType: "number",
              id: 8,
              choices: [],
              hasInput: true,
              prompt: "Min throughput in ops/sec",
              order: 2,
              children: [],
            },
          ],
        },
        {
          UniqueID: "tpl-sub-004",
          display: true,
          description: "Safety requirements",
          type: Type.RequirementObject,
          UPDATED_ON: new Date("2024-06-01"),
          sponsoring_customer: "Boeing Commercial Airplanes",
          node_type: Type.RequirementObject,
          isDeleted2: false,
          header: "2.2 Safety",
          inputType: "multiselect",
          id: 9,
          choices: ["DO-178C", "DO-254", "ARP4754"],
          hasInput: true,
          prompt: "Select applicable standards",
          order: 2,
          children: [],
          Tag: [mockTags[1]],
        },
      ],
      Tag: [mockTags[1]],
    },
    {
      UniqueID: "tpl-sec-003",
      display: true,
      description: "Deliverables schedule",
      type: Type.RequirementObject,
      UPDATED_ON: new Date("2024-06-01"),
      sponsoring_customer: "Boeing Commercial Airplanes",
      node_type: Type.RequirementObject,
      isDeleted2: false,
      header: "3. Deliverables",
      inputType: "section",
      id: 10,
      choices: [],
      hasInput: true,
      prompt: "List deliverables",
      order: 3,
      children: [
        {
          UniqueID: "tpl-sub-005",
          display: true,
          description: "Initial design review",
          type: Type.RequirementObject,
          UPDATED_ON: new Date("2024-06-01"),
          sponsoring_customer: "Boeing Commercial Airplanes",
          node_type: Type.RequirementObject,
          isDeleted2: false,
          header: "3.1 PDR",
          inputType: "date",
          id: 11,
          choices: [],
          hasInput: true,
          prompt: "PDR target date",
          order: 1,
          children: [],
        },
        {
          UniqueID: "tpl-sub-006",
          display: true,
          description: "Critical design review",
          type: Type.RequirementObject,
          UPDATED_ON: new Date("2024-06-01"),
          sponsoring_customer: "Boeing Commercial Airplanes",
          node_type: Type.RequirementObject,
          isDeleted2: false,
          header: "3.2 CDR",
          inputType: "date",
          id: 12,
          choices: [],
          hasInput: true,
          prompt: "CDR target date",
          order: 2,
          children: [],
        },
      ],
      Tag: [],
    },
  ],
  Updated_by: mockUpdatedBy,
  Tag: mockTags,
  order: 0,
};
